- name: ensure podman is installed
  yum:
    name: podman
    state: installed

- name: pull the console image
  podman_image:
    name: quay.io/rmkraus/virtlab-console
    tag: latest
    state: present

- name: ensure the console data directory exists
  file:
    path: /etc/console
    state: directory
    owner: root
    group: root
    mode: 0755
  notify: restart console

- name: parse web shortcut templates
  set_fact:
    url: '{{ item.url | regex_replace("{{\s*student_number\s*}}", "{{ index }}" ) }}'
    name: '{{ item.name | regex_replace("{{\s*student_number\s*}}", "{{ index }}" ) }}'
    desc: '{{ item.desc | regex_replace("{{\s*student_number\s*}}", "{{ index }}" ) }}'
  loop: "{{ console_links }}"
  loop_control:
    label: "{{ item.name }}"
  register: console_links_parsed

- name: create console configuration
  set_fact:
    console_config:
      USER_PASS: "{{ console_user_pass }}"
      ADMIN_PASS: "{{ console_admin_pass }}"
      USER_COUNT: "{{ console_user_count }}"
      DOMAIN: "{{ console_domain }}"
      SECRET_KEY: "{{ console_secret_key }}"
      OTHER_RESOURCES: "{{ console_links_parsed | json_query('results[*].ansible_facts') }}"

- name: ensure the console is configured
  template:
    dest: /etc/console/config.yml
    src: config.yml.j2
    owner: "1000"
    group: "1000"
    mode: 0600
  notify: restart console

- name: ensure ssl certs are loaded
  copy:
    src: "{{ item.src }}"
    dest: "/etc/console/{{ item.dest }}"
    owner: "1000"
    group: "1000"
    mode: "0600"
  loop:
    - src: "{{ console_ssl_cert }}"
      dest: "cert.pem"
    - src: "{{ console_ssl_key }}"
      dest: "privkey.pem"
  loop_control:
    label: "{{ item.dest }}"

- name: create the console container
  command: podman create -d --name console -v /etc/console:/data:Z -p 80:8080 -p 443:8443 quay.io/rmkraus/virtlab-console:latest
  args:
    creates: /etc/systemd/system/console.service

- name: create console service unit file
  command: podman generate systemd --name console
  register: console_unit_file

- name: save console unit file
  copy:
    dest: /etc/systemd/system/console.service
    content: "{{ console_unit_file.stdout }}"

- name: ensure console is running and enabled
  service:
    name: console
    enabled: yes
    state: started

