- name: ensure podman is installed
  yum:
    name: podman
    state: installed

- name: pull the console image
  podman_image:
    name: quay.io/rmkraus/virtlab-console
    tag: latest
    state: present

- name: ensure the console data directory exists
  file:
    path: /etc/console
    state: directory
    owner: root
    group: root
    mode: 0755

- name: ensure the console is configured
  template:
    dest: /etc/console/config.yml
    src: config.yml.j2
    owner: "1000"
    group: "1000"
    mode: 0600

- name: create the console container
  command: podman create -d --name console -v /etc/console:/data:Z -p 80:8080 quay.io/rmkraus/virtlab-console:latest
  args:
    creates: /etc/systemd/system/console.service

- name: create console service unit file
  command: podman generate systemd --name console > /etc/systemd/system/console.service
  args:
    creates: /etc/systemd/system/console.service

- name: ensure console is running and enabled
  service:
    name: console
    enabled: yes
    state: started

