- name: ensure terraform infrastructure has been built
  terraform:
    project_path: "/app/tf/"
    state: present
  when: infrastructure_action != 'destroy'
  tags:
    - terraform
    - infrastructure

- name: ensure terraform infrastructure has been destroyed
  terraform:
    project_path: "/app/tf/"
    state: absent
  when: infrastructure_action == 'destroy'
  tags:
    - terraform
    - infrastructure

