- name: ensure terraform infrastructure has been built
  terraform:
    project_path: "/app/tf/"
    state: present
    targets: "{{ infrastructure_targets }}"
  when: infrastructure_action != 'destroy'
  tags:
    - terraform
    - infrastructure

- name: ensure terraform infrastructure has been destroyed
  terraform:
    project_path: "/app/tf/"
    state: absent
    targets: "{{ infrastructure_targets }}"
  when: infrastructure_action == 'destroy'
  tags:
    - terraform
    - infrastructure

