#!/usr/bin/ansible-playbook
---
- name: bootstrap
  gather_facts: no
  hosts: localhost

  roles:
    - name: keypair
    - name: infrastructure
    - name: inventory
      inventory_win_node_count: "{{ lookup('env', 'WIN_NODE_COUNT') }}"
      inventory_lab_prefix: "{{ lookup('env', 'LAB_PREFIX') }}"
      inventory_domain: "{{ lookup('env', 'AWS_R53_DOMAIN') }}"
      inventory_admin_password: "{{ lookup('env', 'ADMIN_PASSWORD') }}"
    - name: letsencrypt
      letsencrypt_workdir: /data/letsencrypt
      letsencrypt_fqdn: "*.{{ lookup('env', 'LAB_PREFIX') }}.{{ lookup('env', 'AWS_R53_DOMAIN') }}"
      letsencrypt_email: "{{ lookup('env', 'ADMIN_EMAIL') }}"
      letsencrypt_r53_zone: "{{ lookup('env', 'AWS_R53_DOMAIN') }}"


- name: configure windows hosts
  gather_facts: no
  hosts: windows

  roles:
    - name: available
    - name: winusers
      winusers_password: "{{ lookup('env', 'USER_PASSWORD') }}"
    - name: dcvcert
      dcvcert_key: /data/letsencrypt/privkey.pem
      dcvcert_cert: /data/letsencrypt/cert.pem
    - name: putty
      putty_ssh_shortcuts: "{{ lookup('env', 'SSH_SHORTCUTS') | from_json }}"
    - name: links
      links: "{{ lookup('env', 'WWW_SHORTCUTS') | from_json }}"
    - name: firefox
    #- name: winpatch

- name: configure console
  gather_facts: no
  hosts: console

  roles:
    - name: available
    #- name: patch
    - name: console
      console_user_pass: "{{ lookup('env', 'USER_PASSWORD') }}"
      console_admin_pass: "{{ lookup('env', 'ADMIN_PASSWORD') }}"
      console_domain: "{{ lookup('env', 'LAB_PREFIX') + '.' + lookup('env', 'AWS_R53_DOMAIN') }}"
      console_secret_key: "{{ lookup('env', 'ADMIN_PASSWORD') }}"
      console_user_count: "{{ lookup('env', 'WIN_NODE_COUNT') }}"
      console_ssl_cert: /data/letsencrypt/cert.pem
      console_ssl_key: /data/letsencrypt/privkey.pem
      console_links: "{{ lookup('env', 'WWW_SHORTCUTS') | from_json }}"
