#!/usr/bin/ansible-playbook
---
- name: destroy
  gather_facts: no
  hosts: localhost

  roles:
    - name: infrastructure
      infrastructure_action: destroy
      infrastructure_targets: aws_instance.console
